#!/bin/sh

# place ObjNL.lsp at the bottom
newlispdoc ../dragonfly-framework/dragonfly.lsp `find -E ../dragonfly-framework/lib -regex "[./a-z_-]+lsp" | xargs` ../dragonfly-framework/lib/ObjNL.lsp

if [ ! -d ./DF.DB ] ; then
	mkdir -v DF.DB
fi

# we link to DF.DB etc from the guide on included plugins

cd DF.DB

newlispdoc ../../dragonfly-framework/plugins-inactive/db/*.lsp

cd ..

if [ ! -d ./SMTP ] ; then
	mkdir -v SMTP
fi

cd SMTP

newlispdoc ../../dragonfly-framework/plugins-inactive/smtp.lsp

cd ..

