#!/bin/sh

# place ObjNL.lsp at the bottom
newlispdoc ../dragonfly-framework/dragonfly.lsp `find -E ../dragonfly-framework/lib -regex "[./a-z_-]+lsp" | xargs` ../dragonfly-framework/lib/ObjNL.lsp

if [ ! -d ./db ] ; then
	mkdir -v db
fi

# we link to db etc from the guide on included plugins

cd db

newlispdoc ../../dragonfly-framework/plugins-inactive/db/*.lsp

cd ..

if [ ! -d ./smtp ] ; then
	mkdir -v smtp
fi

cd smtp

newlispdoc ../../dragonfly-framework/plugins-inactive/smtp.lsp

cd ..

