#!/bin/sh

NEWLISP_REDIRECTION="./dragonfly-framework/newlisp-redirection.lsp"

if [ ! -f $NEWLISP_REDIRECTION ] ; then
	echo "ERROR: cannot find file: $NEWLISP_REDIRECTION"
	exit 1
fi

# we need to tail this log file because newlisp doesn't output println commands
tail -F -n 0 ./dragonfly-framework/dragonfly.log &
tail_pid=$!

trap "kill $tail_pid" SIGINT SIGHUP SIGTERM

echo "If all goes well visit http://localhost:8080 in your browser"
newlisp "$NEWLISP_REDIRECTION" -http -d 8080 -w . $*
